############################################
#                Lazury NPC                #
#                  Module                  #
############################################

npcs:
  1:
    name: "&bAide"
    world: "hcf01"
    location: "0,71,60"

